Repository BeatnikStation/BeatnikStation, pull requests merged in 2019-01, with the labels that each got.

#11 increasing clown impact on being consumed by singulo
  code/modules/mob/living/carbon/human/human.dm
Labels: Very Important

#17 CDN WOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
  code/_globalvars/misc.dm
  code/game/world.dm
  code/modules/client/client procs.dm
Labels: Very Important, enhancement

#32 mmmmm make that upload limit up up 10MB
  code/modules/client/client procs.dm
Labels: Feature

#34 CDN revert
  code/_compile_options.dm
Labels: Removal/Revert

#37 3 in 1 security fix
  _maps/map_files/TgStation/tgstation.2.1.3.dmm
  code/__DEFINES/math.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/pipe/pipe_dispenser.dm
  code/modules/research/designs/comp_board_designs.dm
Labels: Exploit, Feature, Fix, High Priority, Removal/Revert

#39 Example config attempt 2
  .gitignore
  config/example/access levels.txt
  config/example/admin_nicknames.txt
  config/example/admin_ranks.txt
  config/example/admins.txt
  config/example/config.txt
  config/example/dbconfig.txt
  config/example/external_rsc_urls.txt
  config/example/game_options.txt
  config/example/jobs.txt
  config/example/mentors.txt
  config/example/motd.txt
  config/example/names/adjectives.txt
  config/example/names/ai.txt
  config/example/names/clown.txt
  config/example/names/death_commando.txt
  config/example/names/first.txt
  config/example/names/first_female.txt
  config/example/names/first_male.txt
  config/example/names/last.txt
  config/example/names/lizard_female.txt
  config/example/names/lizard_male.txt
  config/example/names/mime.txt
  config/example/names/moth_female.txt
  config/example/names/moth_male.txt
  config/example/names/ninjaname.txt
  config/example/names/ninjatitle.txt
  config/example/names/verbs.txt
  config/example/names/wizardfirst.txt
  config/example/names/wizardsecond.txt
  config/example/silicon_laws.txt
  config/example/space_levels.txt
  config/example/tips.txt
Labels: Config/SQL Change, Feature, Fix, High Priority

#43 T H I C C S C R E E N
  code/__DEFINES/math.dm
  code/__HELPERS/unsorted.dm
  code/controllers/configuration.dm
  code/game/mecha/combat/marauder.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/mob/login.dm
  code/modules/projectiles/firing.dm
  config/example/config.txt
  interface/skin.dmf
Labels: Feature
